<div class="row">

  <div class="span8">
    
    <div class="page-header">
      <h1>About <small>me, this site and what I want.</small></h1>
    </div>
    
    <p>
      My name is Joel Söderberg. Citizen of the northern kingdom of Sweden, 
      web developer and übergeek. So most of the content here will be about
      those two things (Well geekyness is a lot of thing), and reposts from
      Reddit. I decided to do all the writing in english. Which is crazy,
      but fun. Hopefully I'll make fewer spelling and grammar mistakes as time
      progresses. I can't promise some of the texts and links won't be in
      swedish sometimes though.
    </p> 
    
    <p>
      This site began as a weekend project to write a super simple, low memory
      blog tool. I call it <a href="https://github.com/bohemel/LoLa">LoLa</a>! 
      In my main work at <a href="http://understandit.se">Understandit</a> I 
      develop sites in <a href="http://drupal.org/">Drupal</a>, and I feelt I
      needed a little break from the impressive beast Drupal is (with all the 
      contrib modules etc. etc.). So I wanted to create the opposite. 
      Something completely ungeneric (is that even a word?).
    </p>
    
    <p>
      I developed (is developing actually) the tool. So I thought I really 
      should start filling it with some kind of content. We'll see where it
      ends.
    <p>
      
  </div>

</div>