<div class="row">
  <div class="span8">
    <div class="page-header">
      <h1>Contact <small>me, or someone you really like.</small></h1>
    </div>
    <p>
      <strong>I'm not afraid of no spam!</strong> So you can reach me at:
    </p>
    <p>
      <span class="panspam">
        <span class="u">joel</span>
        [at]
        <span class="d">joelsoderberg [dot] se</span>
      </span>
    </p>
  </div>
</div>