<div class="page-header">
  <h1>Create new post</h1>
</div>
<div class="row">
  <div class="span12">
    <form class="well" method="post" action="/post/create">
      <label>Title</label>
      <input name="title" />
      <label>Content</label>
      <textarea style="width: 99%;" rows="20" name="content"></textarea>
      <label>Tags</label>
      <input name="tags" />
      <div>
        <button type="submit" class="btn">Submit</button>
      </div>
    </form>
  </div>
</div>
